### ISSUE TITLE
集群ssh支持

### ISSUE THREAD

**Issue by travishao** [libsgh/redis_admin#3]
请问jedisCluster有支持ssh隧道吗？

我这边测试映射了所有集群中所有节点的端口到本地，创建集群的时候又被默认覆盖成默认节点的HOST：PORT，  这种问题……

**Comment by libsgh** [comment]
1. jedisCluster 之前我在github上提过issues，官方说目前不支持，现在没有在跟踪了，抽空我看一下。
2. 每个连接都是独立的，互相不会影响，如果是页面BUG请加个图片说明一下。
3. 这个很久没有在维护了，不知道你目前的使用场景是什么。

**Comment by travishao** [comment]
不是你这项目的bug，是想开个issue跟你讨论一下。
我看了源码，jedis官方集群确实不支持ssh，我找遍了百度、谷歌、github都没有找到有人这么做的，可能jedis使用者不会有这样的需求，这方面没有资料可以参考。

我自己有开发一个redis客户端工具（Redis Viewer），当然要ssh功能了，毕竟很多运维会需要用。
重点是：昨天这个问题我这边已经解决jedis包集群不能ssh的问题了，有兴趣来群里我们讨论讨论

点击链接加入群聊【RedisViewer交流群859391052】：https://jq.qq.com/?_wv=1027&k=5cfywla
支持SSH集群、单机，欢迎试用讨论~

**Comment by libsgh** [comment]
开源项目吗，甩个项目链接，看下源码啊

**Comment by travishao** [comment]
暂时没有开源，自己玩儿的做的东西
